from window_class import class_window as window
from data_api import nc_data as data


class AxisDataWindow(window.WindowTable):
    def __init__(self):
        super().__init__()

    def init_table(self):
        # [3000] 轴使能
        for item in data.axis_enabled:
            self.add_item(item)

        # [3001] 轴回参考点
        for item in data.axis_homed:
            self.add_item(item)

        # [3002] 轴当前位置-MCS machine units
        for item in data.actual_position:
            self.add_item(item)

        # [3003] 轴目标位置-MCS
        for item in data.axis_target_position:
            self.add_item(item)

        self.add_item(data.x_velocity)
        self.add_item(data.y_velocity)
        self.add_item(data.z_velocity)
        self.add_item(data.a_velocity)
        self.add_item(data.b_velocity)
        self.add_item(data.c_velocity)
        self.add_item(data.u_velocity)
        self.add_item(data.v_velocity)
        self.add_item(data.w_velocity)
        # [3001] 轴回参考点
        for item in data.axis_homed:
            self.add_item(item)

        # [3004] 轴余程-MCS
        for item in data.axis_remaining_distance:
            self.add_item(item)

        self.add_item(data.x_velocity)
        self.add_item(data.y_velocity)
        self.add_item(data.z_velocity)
        self.add_item(data.a_velocity)
        self.add_item(data.b_velocity)
        self.add_item(data.c_velocity)
        self.add_item(data.u_velocity)
        self.add_item(data.v_velocity)
        self.add_item(data.w_velocity)
        self.add_item(data.feedrate)
        self.add_item(data.joint_0_ferror)
        self.add_item(data.joint_1_ferror)
        self.add_item(data.joint_2_ferror)
        self.add_item(data.joint_3_ferror)
        self.add_item(data.joint_4_ferror)
        self.add_item(data.joint_5_ferror)
        self.add_item(data.joint_6_ferror)
        self.add_item(data.joint_7_ferror)
        self.add_item(data.joint_8_ferror)
        self.add_item(data.spindle_0_speed)
        self.add_item(data.spindle_0_enable)
        self.add_item(data.spindle_0_rate)
        self.add_item(data.current_feed_velocity)
        # 配置数据
        self.add_item(data.x_rotary_units)
        self.add_item(data.y_rotary_units)
        self.add_item(data.z_rotary_units)
        self.add_item(data.a_rotary_units)
        self.add_item(data.b_rotary_units)
        self.add_item(data.c_rotary_units)
        self.add_item(data.u_rotary_units)
        self.add_item(data.v_rotary_units)
        self.add_item(data.w_rotary_units)
        self.add_item(data.x_locking_joint)
        self.add_item(data.y_locking_joint)
        self.add_item(data.z_locking_joint)
        self.add_item(data.a_locking_joint)
        self.add_item(data.b_locking_joint)
        self.add_item(data.c_locking_joint)
        self.add_item(data.u_locking_joint)
        self.add_item(data.v_locking_joint)
        self.add_item(data.w_locking_joint)
        self.add_item(data.x_offset_ratio)
        self.add_item(data.y_offset_ratio)
        self.add_item(data.z_offset_ratio)
        self.add_item(data.a_offset_ratio)
        self.add_item(data.b_offset_ratio)
        self.add_item(data.c_offset_ratio)
        self.add_item(data.u_offset_ratio)
        self.add_item(data.v_offset_ratio)
        self.add_item(data.w_offset_ratio)
        self.add_item(data.joint_0_type)
        self.add_item(data.joint_1_type)
        self.add_item(data.joint_2_type)
        self.add_item(data.joint_3_type)
        self.add_item(data.joint_4_type)
        self.add_item(data.joint_5_type)
        self.add_item(data.joint_6_type)
        self.add_item(data.joint_7_type)
        self.add_item(data.joint_8_type)
        self.add_item(data.joint_0_max_velocity)
        self.add_item(data.joint_1_max_velocity)
        self.add_item(data.joint_2_max_velocity)
        self.add_item(data.joint_3_max_velocity)
        self.add_item(data.joint_4_max_velocity)
        self.add_item(data.joint_5_max_velocity)
        self.add_item(data.joint_6_max_velocity)
        self.add_item(data.joint_7_max_velocity)
        self.add_item(data.joint_8_max_velocity)
        self.add_item(data.joint_0_max_acceleration)
        self.add_item(data.joint_1_max_acceleration)
        self.add_item(data.joint_2_max_acceleration)
        self.add_item(data.joint_3_max_acceleration)
        self.add_item(data.joint_4_max_acceleration)
        self.add_item(data.joint_5_max_acceleration)
        self.add_item(data.joint_6_max_acceleration)
        self.add_item(data.joint_7_max_acceleration)
        self.add_item(data.joint_8_max_acceleration)
        self.add_item(data.joint_0_backlash)
        self.add_item(data.joint_1_backlash)
        self.add_item(data.joint_2_backlash)
        self.add_item(data.joint_3_backlash)
        self.add_item(data.joint_4_backlash)
        self.add_item(data.joint_5_backlash)
        self.add_item(data.joint_6_backlash)
        self.add_item(data.joint_7_backlash)
        self.add_item(data.joint_8_backlash)
        self.add_item(data.joint_0_min_limit)
        self.add_item(data.joint_1_min_limit)
        self.add_item(data.joint_2_min_limit)
        self.add_item(data.joint_3_min_limit)
        self.add_item(data.joint_4_min_limit)
        self.add_item(data.joint_5_min_limit)
        self.add_item(data.joint_6_min_limit)
        self.add_item(data.joint_7_min_limit)
        self.add_item(data.joint_8_min_limit)
        self.add_item(data.joint_0_max_limit)
        self.add_item(data.joint_1_max_limit)
        self.add_item(data.joint_2_max_limit)
        self.add_item(data.joint_3_max_limit)
        self.add_item(data.joint_4_max_limit)
        self.add_item(data.joint_5_max_limit)
        self.add_item(data.joint_6_max_limit)
        self.add_item(data.joint_7_max_limit)
        self.add_item(data.joint_8_max_limit)
        self.add_item(data.joint_0_min_ferror)
        self.add_item(data.joint_1_min_ferror)
        self.add_item(data.joint_2_min_ferror)
        self.add_item(data.joint_3_min_ferror)
        self.add_item(data.joint_4_min_ferror)
        self.add_item(data.joint_5_min_ferror)
        self.add_item(data.joint_6_min_ferror)
        self.add_item(data.joint_7_min_ferror)
        self.add_item(data.joint_8_min_ferror)
        self.add_item(data.joint_0_max_ferror)
        self.add_item(data.joint_1_max_ferror)
        self.add_item(data.joint_2_max_ferror)
        self.add_item(data.joint_3_max_ferror)
        self.add_item(data.joint_4_max_ferror)
        self.add_item(data.joint_5_max_ferror)
        self.add_item(data.joint_6_max_ferror)
        self.add_item(data.joint_7_max_ferror)
        self.add_item(data.joint_8_max_ferror)
        self.add_item(data.joint_0_is_locking)
        self.add_item(data.joint_1_is_locking)
        self.add_item(data.joint_2_is_locking)
        self.add_item(data.joint_3_is_locking)
        self.add_item(data.joint_4_is_locking)
        self.add_item(data.joint_5_is_locking)
        self.add_item(data.joint_6_is_locking)
        self.add_item(data.joint_7_is_locking)
        self.add_item(data.joint_8_is_locking)
        self.add_item(data.joint_0_home_position)
        self.add_item(data.joint_1_home_position)
        self.add_item(data.joint_2_home_position)
        self.add_item(data.joint_3_home_position)
        self.add_item(data.joint_4_home_position)
        self.add_item(data.joint_5_home_position)
        self.add_item(data.joint_6_home_position)
        self.add_item(data.joint_7_home_position)
        self.add_item(data.joint_8_home_position)
        self.add_item(data.joint_0_home_offset)
        self.add_item(data.joint_1_home_offset)
        self.add_item(data.joint_2_home_offset)
        self.add_item(data.joint_3_home_offset)
        self.add_item(data.joint_4_home_offset)
        self.add_item(data.joint_5_home_offset)
        self.add_item(data.joint_6_home_offset)
        self.add_item(data.joint_7_home_offset)
        self.add_item(data.joint_8_home_offset)
        self.add_item(data.joint_0_home_search_vel)
        self.add_item(data.joint_1_home_search_vel)
        self.add_item(data.joint_2_home_search_vel)
        self.add_item(data.joint_3_home_search_vel)
        self.add_item(data.joint_4_home_search_vel)
        self.add_item(data.joint_5_home_search_vel)
        self.add_item(data.joint_6_home_search_vel)
        self.add_item(data.joint_7_home_search_vel)
        self.add_item(data.joint_8_home_search_vel)
        self.add_item(data.joint_0_home_latch_vel)
        self.add_item(data.joint_1_home_latch_vel)
        self.add_item(data.joint_2_home_latch_vel)
        self.add_item(data.joint_3_home_latch_vel)
        self.add_item(data.joint_4_home_latch_vel)
        self.add_item(data.joint_5_home_latch_vel)
        self.add_item(data.joint_6_home_latch_vel)
        self.add_item(data.joint_7_home_latch_vel)
        self.add_item(data.joint_8_home_latch_vel)
        self.add_item(data.joint_0_home_final_vel)
        self.add_item(data.joint_1_home_final_vel)
        self.add_item(data.joint_2_home_final_vel)
        self.add_item(data.joint_3_home_final_vel)
        self.add_item(data.joint_4_home_final_vel)
        self.add_item(data.joint_5_home_final_vel)
        self.add_item(data.joint_6_home_final_vel)
        self.add_item(data.joint_7_home_final_vel)
        self.add_item(data.joint_8_home_final_vel)
        self.add_item(data.joint_0_home_use_index_pulse)
        self.add_item(data.joint_1_home_use_index_pulse)
        self.add_item(data.joint_2_home_use_index_pulse)
        self.add_item(data.joint_3_home_use_index_pulse)
        self.add_item(data.joint_4_home_use_index_pulse)
        self.add_item(data.joint_5_home_use_index_pulse)
        self.add_item(data.joint_6_home_use_index_pulse)
        self.add_item(data.joint_7_home_use_index_pulse)
        self.add_item(data.joint_8_home_use_index_pulse)
        self.add_item(data.joint_0_home_encoder_reset)
        self.add_item(data.joint_1_home_encoder_reset)
        self.add_item(data.joint_2_home_encoder_reset)
        self.add_item(data.joint_3_home_encoder_reset)
        self.add_item(data.joint_4_home_encoder_reset)
        self.add_item(data.joint_5_home_encoder_reset)
        self.add_item(data.joint_6_home_encoder_reset)
        self.add_item(data.joint_7_home_encoder_reset)
        self.add_item(data.joint_8_home_encoder_reset)
        self.add_item(data.joint_0_absolute_encoder)
        self.add_item(data.joint_1_absolute_encoder)
        self.add_item(data.joint_2_absolute_encoder)
        self.add_item(data.joint_3_absolute_encoder)
        self.add_item(data.joint_4_absolute_encoder)
        self.add_item(data.joint_5_absolute_encoder)
        self.add_item(data.joint_6_absolute_encoder)
        self.add_item(data.joint_7_absolute_encoder)
        self.add_item(data.joint_8_absolute_encoder)
        self.add_item(data.joint_0_home_sequence)
        self.add_item(data.joint_1_home_sequence)
        self.add_item(data.joint_2_home_sequence)
        self.add_item(data.joint_3_home_sequence)
        self.add_item(data.joint_4_home_sequence)
        self.add_item(data.joint_5_home_sequence)
        self.add_item(data.joint_6_home_sequence)
        self.add_item(data.joint_7_home_sequence)
        self.add_item(data.joint_8_home_sequence)
        for item in data.spindle_max_forward_vel:
            self.add_item(item)
        for item in data.spindle_max_reverse_vel:
            self.add_item(item)
        for item in data.spindle_increment:
            self.add_item(item)
        for item in data.spindle_home_vel:
            self.add_item(item)
        self.add_item(data.axis_count)
        # self.add_item(data.joint_0_backlash_setting)
        # self.add_item(data.joint_1_backlash_setting)
        # self.add_item(data.joint_2_backlash_setting)
        # self.add_item(data.joint_3_backlash_setting)
        # self.add_item(data.joint_4_backlash_setting)
        # self.add_item(data.joint_5_backlash_setting)
        # self.add_item(data.joint_6_backlash_setting)
        # self.add_item(data.joint_7_backlash_setting)
        # self.add_item(data.joint_8_backlash_setting)
        self.add_item(data.joint_0_pitch_comp_setting)
        self.add_item(data.joint_1_pitch_comp_setting)
        self.add_item(data.joint_2_pitch_comp_setting)
        self.add_item(data.joint_3_pitch_comp_setting)
        self.add_item(data.joint_4_pitch_comp_setting)
        self.add_item(data.joint_5_pitch_comp_setting)
        self.add_item(data.joint_6_pitch_comp_setting)
        self.add_item(data.joint_7_pitch_comp_setting)
        self.add_item(data.joint_8_pitch_comp_setting)
        self.add_item(data.joint_0_pitch_comp_type)
        self.add_item(data.joint_1_pitch_comp_type)
        self.add_item(data.joint_2_pitch_comp_type)
        self.add_item(data.joint_3_pitch_comp_type)
        self.add_item(data.joint_4_pitch_comp_type)
        self.add_item(data.joint_5_pitch_comp_type)
        self.add_item(data.joint_6_pitch_comp_type)
        self.add_item(data.joint_7_pitch_comp_type)
        self.add_item(data.joint_8_pitch_comp_type)
        # self.add_item(data.axis_0_cmdPos)
        # self.add_item(data.axis_1_cmdPos)
        # self.add_item(data.axis_2_cmdPos)
        # self.add_item(data.axis_3_cmdPos)
        # self.add_item(data.axis_4_cmdPos)
        # self.add_item(data.axis_5_cmdPos)
        # self.add_item(data.axis_6_cmdPos)
        # self.add_item(data.axis_7_cmdPos)
        # self.add_item(data.axis_8_cmdPos)
        self.add_item(data.axis_list)
        self.add_item(data.axis_0_accel)
        self.add_item(data.axis_1_accel)
        self.add_item(data.axis_2_accel)

        self.add_item(data.program_name)
        self.add_item(data.program_line)
        self.add_item(data.rcs_state)

        # [3140] 轴-手动快速最大速度
        for item in data.axis_jog_speed_rapid_max:
            self.add_item(item)

        # [3141] 轴-手动进给最大速度
        for item in data.axis_jog_speed_feed_max:
            self.add_item(item)

        # 轴诊断-轴信息-扭矩
        self.add_item(data.axis_0_torque)
        self.add_item(data.axis_1_torque)
        self.add_item(data.axis_2_torque)
        self.add_item(data.axis_3_torque)
        self.add_item(data.axis_4_torque)
        self.add_item(data.axis_5_torque)
        self.add_item(data.axis_6_torque)
        self.add_item(data.axis_7_torque)
        self.add_item(data.axis_8_torque)
        self.add_item(data.axis_99_torque)
        # 轴诊断-轴信息-轴补偿值(速度)
        self.add_item(data.axis_0_backlash_vel)
        self.add_item(data.axis_1_backlash_vel)
        self.add_item(data.axis_2_backlash_vel)
        self.add_item(data.axis_3_backlash_vel)
        self.add_item(data.axis_4_backlash_vel)
        self.add_item(data.axis_5_backlash_vel)
        self.add_item(data.axis_6_backlash_vel)
        self.add_item(data.axis_7_backlash_vel)
        self.add_item(data.axis_8_backlash_vel)
        self.add_item(data.axis_99_backlash_vel)
        # 轴诊断-轴信息-轴补偿值(差值)
        self.add_item(data.axis_0_backlash_filt)
        self.add_item(data.axis_1_backlash_filt)
        self.add_item(data.axis_2_backlash_filt)
        self.add_item(data.axis_3_backlash_filt)
        self.add_item(data.axis_4_backlash_filt)
        self.add_item(data.axis_5_backlash_filt)
        self.add_item(data.axis_6_backlash_filt)
        self.add_item(data.axis_7_backlash_filt)
        self.add_item(data.axis_8_backlash_filt)
        self.add_item(data.axis_99_backlash_filt)
        # 轴诊断-轴信息-轴补偿值(原始值)
        self.add_item(data.axis_0_backlash_corr)
        self.add_item(data.axis_1_backlash_corr)
        self.add_item(data.axis_2_backlash_corr)
        self.add_item(data.axis_3_backlash_corr)
        self.add_item(data.axis_4_backlash_corr)
        self.add_item(data.axis_5_backlash_corr)
        self.add_item(data.axis_6_backlash_corr)
        self.add_item(data.axis_7_backlash_corr)
        self.add_item(data.axis_8_backlash_corr)
        self.add_item(data.axis_99_backlash_corr)
        # 轴诊断-轴信息-轴跟踪误差(最大值)
        self.add_item(data.axis_0_err_maxLimit)
        self.add_item(data.axis_1_err_maxLimit)
        self.add_item(data.axis_2_err_maxLimit)
        self.add_item(data.axis_3_err_maxLimit)
        self.add_item(data.axis_4_err_maxLimit)
        self.add_item(data.axis_5_err_maxLimit)
        self.add_item(data.axis_6_err_maxLimit)
        self.add_item(data.axis_7_err_maxLimit)
        self.add_item(data.axis_8_err_maxLimit)
        self.add_item(data.axis_99_err_maxLimit)
        # 轴诊断-轴信息-轴跟踪误差(最小值)
        self.add_item(data.axis_0_err_minLimit)
        self.add_item(data.axis_1_err_minLimit)
        self.add_item(data.axis_2_err_minLimit)
        self.add_item(data.axis_3_err_minLimit)
        self.add_item(data.axis_4_err_minLimit)
        self.add_item(data.axis_5_err_minLimit)
        self.add_item(data.axis_6_err_minLimit)
        self.add_item(data.axis_7_err_minLimit)
        self.add_item(data.axis_8_err_minLimit)
        self.add_item(data.axis_99_err_minLimit)
        # 轴诊断-轴信息-目标位置
        self.add_item(data.axis_0_tarpos)
        self.add_item(data.axis_1_tarpos)
        self.add_item(data.axis_2_tarpos)
        self.add_item(data.axis_3_tarpos)
        self.add_item(data.axis_4_tarpos)
        self.add_item(data.axis_5_tarpos)
        self.add_item(data.axis_6_tarpos)
        self.add_item(data.axis_7_tarpos)
        self.add_item(data.axis_8_tarpos)
        self.add_item(data.axis_99_tarpos)
        # 轴诊断-轴信息-反馈位置
        self.add_item(data.axis_0_actpos)
        self.add_item(data.axis_1_actpos)
        self.add_item(data.axis_2_actpos)
        self.add_item(data.axis_3_actpos)
        self.add_item(data.axis_4_actpos)
        self.add_item(data.axis_5_actpos)
        self.add_item(data.axis_6_actpos)
        self.add_item(data.axis_7_actpos)
        self.add_item(data.axis_8_actpos)
        self.add_item(data.axis_99_actpos)
        # 轴诊断-轴信息-目标速度
        self.add_item(data.axis_0_tarvel)
        self.add_item(data.axis_1_tarvel)
        self.add_item(data.axis_2_tarvel)
        self.add_item(data.axis_3_tarvel)
        self.add_item(data.axis_4_tarvel)
        self.add_item(data.axis_5_tarvel)
        self.add_item(data.axis_6_tarvel)
        self.add_item(data.axis_7_tarvel)
        self.add_item(data.axis_8_tarvel)
        self.add_item(data.axis_99_tarvel)
        # 轴诊断-轴信息-反馈速度
        self.add_item(data.axis_0_actvel)
        self.add_item(data.axis_1_actvel)
        self.add_item(data.axis_2_actvel)
        self.add_item(data.axis_3_actvel)
        self.add_item(data.axis_4_actvel)
        self.add_item(data.axis_5_actvel)
        self.add_item(data.axis_6_actvel)
        self.add_item(data.axis_7_actvel)
        self.add_item(data.axis_8_actvel)
        self.add_item(data.axis_99_actvel)
        # 主轴-最小正向转速
        for item in data.spindle_min_forward_vel:
            self.add_item(item)
        # 主轴-最小反向转速
        for item in data.spindle_min_reverse_vel:
            self.add_item(item)
        # 主轴-PID
        for item in data.spindle_pid_p:
            self.add_item(item)
        for item in data.spindle_pid_i:
            self.add_item(item)
        for item in data.spindle_pid_d:
            self.add_item(item)

        # [3166] 轴编码器每转线数
        for item in data.axis_encoder_lrp:
            self.add_item(item)
        # [3167] 轴电子齿轮比分子
        for item in data.axis_gear_molecule:
            self.add_item(item)
        # [3168] 轴电子齿轮比分母
        for item in data.axis_gear_deniminator:
            self.add_item(item)
        # [3169] 轴丝杆螺距
        for item in data.axis_flight_lead:
            self.add_item(item)

        # [3186] 轴运动方向
        for item in data.axis_motion_dir:
            self.add_item(item)

        # [3187] 主轴点动进给最大速度
        for item in data.spindle_jogSpeed_feed_max:
            self.add_item(item)
        # [3188] 主轴点动快速最大速度
        for item in data.spindle_jogSpeed_rapid_max:
            self.add_item(item)
        # [318900] 刀库轴点动快速最大速度
        self.add_item(data.tool_jogSpeed_rapid_max)
        # [318901] 刀库轴点动进给最大速度
        self.add_item(data.tool_jogSpeed_feed_max)

        # [319100] 主轴的轴机械传动比分母
        self.add_item(data.spindle_transmission_denominator)
        # [319101] 主轴的丝杆螺距
        self.add_item(data.spindle_screw_pitch)
        # [319102] 主轴的轴机械传动比分子
        self.add_item(data.spindle_transmission_numerator)
        # [319103] 主轴的线转数
        self.add_item(data.spindle_line_revolution_counts)
        # [319104] 主轴的运动方向
        self.add_item(data.spindle_motion_orientation)
        # [319105] 主轴速度模式下齿轮比
        self.add_item(data.spindle_velocity_mode_gear_ratio)
        # [319106] 主轴速度模式下运动方向
        self.add_item(data.spindle_velocity_mode_motion_orientation)
